### ISSUE TITLE
Problem with QRNN num_layers=2, layers=None, and input_size != hidden_size

### ISSUE THREAD

**Issue by ceshine** [salesforce/pytorch-qrnn#10]
This code will not work:
```
import torch
from torchqrnn import QRNN

seq_len, batch_size, hidden_size = 7, 20, 256
size = (seq_len, batch_size, 32)
X = torch.autograd.Variable(torch.rand(size), requires_grad=True).cuda()
print(X.size())

qrnn = QRNN(32, hidden_size, num_layers=2, dropout=0.4)
qrnn.cuda()
output, hidden = qrnn(X)

print(output.size(), hidden.size())
```

I think the problem is caused by this line:

https://github.com/salesforce/pytorch-qrnn/blob/b64688071e947451ac0dab2d1ac9ef73673406f8/torchqrnn/qrnn.py#L142

Aren't the initialization parameters supposed to be `QRNNLayer(hidden_size, hidden_size, **kwargs)` starting from the second layer?

**Comment by Smerity** [comment]
Hi @ceshine! Thanks for reporting the bug and I'm sorry it caught you!

You're entirely correct - the first value should be `input_size` on the first layer and `hidden_size` on all subsequent layers. I have committed a fix that should solve the problem.

If you run `pip install -U git+https://github.com/salesforce/pytorch-qrnn` you should find the error fixed. If you have any other issues don't hesitate to reach out though!
