### ISSUE TITLE
[WinError 126] The specified module could not be found - Can you please help figure out why is the sample code you provided to run QRNN is failing?

### ISSUE THREAD

**Issue by issararab** [salesforce/pytorch-qrnn#28]
I am trying to replace my LSTM architecture with your interesting QRNN. I followed the steps in the readme file. Everything is installed successfully but when I run the toy example on my jupyter notebook, I keep getting this issue. Would you please help to figure out the problem?

============================================================

C:\Users\issar\Anaconda3\lib\site-packages\torch\nn\functional.py:1339: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
C:\Users\issar\Anaconda3\lib\site-packages\torch\nn\functional.py:1350: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
..\torch\csrc\autograd\python_function.cpp:638: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-65b420ff98d9> in <module>
      8 qrnn = QRNN(hidden_size, hidden_size, num_layers=2, dropout=0.4)
      9 qrnn.cuda()
---> 10 output, hidden = qrnn(X)
     11 
     12 print(output.size(), hidden.size())

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

~\Anaconda3\lib\site-packages\torchqrnn\qrnn.py in forward(self, input, hidden)
    162 
    163         for i, layer in enumerate(self.layers):
--> 164             input, hn = layer(input, None if hidden is None else hidden[i])
    165             next_hidden.append(hn)
    166 

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

~\Anaconda3\lib\site-packages\torchqrnn\qrnn.py in forward(self, X, hidden)
     97         # Forget Mult
     98         # For testing QRNN without ForgetMult CUDA kernel, C = Z * F may be useful
---> 99         C = ForgetMult()(F, Z, hidden, use_cuda=self.use_cuda)
    100 
    101         # Apply (potentially optional) output gate

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

~\Anaconda3\lib\site-packages\torchqrnn\forget_mult.py in forward(self, f, x, hidden_init, use_cuda)
    176         ###
    177         # Avoiding 'RuntimeError: expected a Variable argument, but got NoneType' when hidden_init is None
--> 178         if hidden_init is None: return GPUForgetMult()(f, x) if use_cuda else CPUForgetMult()(f, x)
    179         return GPUForgetMult()(f, x, hidden_init) if use_cuda else CPUForgetMult()(f, x, hidden_init)
    180 

~\Anaconda3\lib\site-packages\torchqrnn\forget_mult.py in forward(self, f, x, hidden_init)
    118 
    119     def forward(self, f, x, hidden_init=None):
--> 120         self.compile()
    121         seq_size, batch_size, hidden_size = f.size()
    122         result = f.new(seq_size + 1, batch_size, hidden_size)

~\Anaconda3\lib\site-packages\torchqrnn\forget_mult.py in compile(self)
    100     def compile(self):
    101         if self.ptx is None:
--> 102             program = Program(kernel.encode(), 'recurrent_forget_mult.cu'.encode())
    103             GPUForgetMult.ptx = program.compile()
    104 

~\Anaconda3\lib\site-packages\pynvrtc\compiler.py in __init__(self, src, name, headers, include_names, lib_name)
     47                  headers=[], include_names=[],
     48                  lib_name=''):
---> 49         self._interface = NVRTCInterface(lib_name)
     50         self._program = self._interface.nvrtcCreateProgram(src, name,
     51                                                            headers,

~\Anaconda3\lib\site-packages\pynvrtc\interface.py in __init__(self, lib_path)
     85     def __init__(self, lib_path=''):
     86         self._lib = None
---> 87         self._load_nvrtc_lib(lib_path)
     88 
     89     def _load_nvrtc_lib(self, lib_path):

~\Anaconda3\lib\site-packages\pynvrtc\interface.py in _load_nvrtc_lib(self, lib_path)
    107             name = lib_path
    108 
--> 109         self._lib = cdll.LoadLibrary(name)
    110 
    111         self._lib.nvrtcCreateProgram.argtypes = [

~\Anaconda3\lib\ctypes\__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

~\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: [WinError 126] The specified module could not be found

**Comment by issararab** [comment]
I am using Cuda V10.0 while nvrtc tries to load nvrtc64_94.dll. Solved by change the default binary file name of pynvrtc to nvrtc64_100_0.dll. Solved

**Comment by amrut-prabhu** [comment]
@issararab Can you let me know the steps to fix this issue? I'm not sure about how to change the default binary file. Thank you!
